---
title: "RegressionSummary"
author: "David"
date: "2024-03-18"
output: pdf_document
---

```{r, include = FALSE}

library(lfe)
library(tidyverse)

```



```{r}
subset <- read_csv("~/Desktop/Portfolio_Trades_my_computer/data_minimizing/working_files/subset.csv")

regr1 <- felm(filled ~ trans_cost + mediancost_insublist + 
                mediancost_outsidesublist | req_id | 0 | req_id, data = subset)
summary1 <- summary(regr1, cluster = c("req_id"))
print(summary1)
```


```{r}
regr2 <- felm(filled ~ trans_cost + mincost_insublist +
                mincost_outsidesublist | req_id | 0 | req_id, data = subset)
summary2 <- summary(regr2, cluster = c("req_id"))
print(summary2)
```

### Simple regression model of filled on trans_cost for non-dealer HY requests 
### *without list fixed effects*
```{r}
model1_fe <- lm(filled ~ trans_cost, data = subset)
summary(model1_fe)
```

### Simple regression model of filled on trans_cost for non-dealer HY requests 
### *with list fixed effects*

This is run with felm, because lm with req_id fixed effect is computationally 
very intensive (vector memory is exceeded)
```{r}
model2_nofe <- felm(filled ~ trans_cost | req_id, data = subset)
summary(model2_nofe)
```

